controlplanes:
  - name: k8s-control-plane-1
    box: generic/ubuntu1804
    hostname: k8s-control-plane-1
    ip: 172.30.1.41
    memory: 2048
    cpu: 2
  - name: k8s-control-plane-2
    box: generic/ubuntu1804
    hostname: k8s-control-plane-2
    ip: 172.30.1.42
    memory: 2048
    cpu: 2
  - name: k8s-control-plane-3
    box: generic/ubuntu1804
    hostname: k8s-control-plane-3
    ip: 172.30.1.43
    memory: 2048
    cpu: 2
  
workers:  
  - name: k8s-worker-1
    box: generic/ubuntu1804
    hostname: k8s-worker-1
    ip: 172.30.1.44
    memory: 2048
    cpu: 2
  
  - name: k8s-worker-2
    box: generic/ubuntu1804
    hostname: k8s-worker-2
    ip: 172.30.1.45
    memory: 2048
    cpu: 2
  
bootstrap:
  - name: k8s-bootstrap
    box: generic/ubuntu1804
    hostname: k8s-bootstrap
    ip: 172.30.1.40
    memory: 2048
    cpu: 2